spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?characterEncoding=UTF-8
    username: hdlend
    password: hdlend123

    
